Tiramisu Compiler: tiramisu::global Class Reference
tiramisu::global Class Reference
A class that holds all the global variables necessary for Tiramisu.
#include <expr.h>
Public Member Functions
global ()
Static Public Member Functions
static function * get_implicit_function ()
Return the implicit function created during Tiramisu initialization.
static void set_implicit_function (function *fct)
Return the implicit function created during Tiramisu initialization.
static void set_auto_data_mapping (bool v)
If this option is set to true, Tiramisu automatically modifies the computation data mapping whenever a new schedule is applied to a computation.
static bool is_auto_data_mapping_set ()
Return whether auto data mapping is set.
static void set_default_tiramisu_options ()
static void set_loop_iterator_type (primitive_t t)
static primitive_t get_loop_iterator_data_type ()
Detailed Description
A class that holds all the global variables necessary for Tiramisu.
It also holds Tiramisu options.
Definition at line 47 of file expr.h.
Constructor & Destructor Documentation
global()
tiramisu::global::global () inline
Definition at line 139 of file expr.h.
References set_default_tiramisu_options().
Member Function Documentation
get_implicit_function()
static function* tiramisu::global::get_implicit_function () inline static
Return the implicit function created during Tiramisu initialization.
When Tiramisu is initialized, an implicit Tiramisu function is created. All the computations and buffers created later are added by deafult to this function unless the user indicates otherwise using the Tiramisu API (by using the low level Tiramisu API and by providing a different function as input to the API).
Definition at line 80 of file expr.h.
get_loop_iterator_data_type()
static primitive_t tiramisu::global::get_loop_iterator_data_type () inline static
Definition at line 134 of file expr.h.
is_auto_data_mapping_set()
static bool tiramisu::global::is_auto_data_mapping_set () inline static
Return whether auto data mapping is set.
If auto data mapping is set, Tiramisu automatically modifies the computation data mapping whenever a new schedule is applied to a computation. If it is set to false, it is up to the user to set the right data mapping before code generation.
Definition at line 119 of file expr.h.
set_auto_data_mapping()
static void tiramisu::global::set_auto_data_mapping (bool v) inline static
If this option is set to true, Tiramisu automatically modifies the computation data mapping whenever a new schedule is applied to a computation.
If it is set to false, it is up to the user to set the right data mapping before code generation.
Definition at line 106 of file expr.h.
Referenced by set_default_tiramisu_options().
set_default_tiramisu_options()
static void tiramisu::global::set_default_tiramisu_options () inline static
Definition at line 124 of file expr.h.
References tiramisu::p_int32, and set_auto_data_mapping().
Referenced by global().
set_implicit_function()
static void tiramisu::global::set_implicit_function (function * fct) inline static
Return the implicit function created during Tiramisu initialization.
When Tiramisu is initialized, an implicit Tiramisu function is created. All the computations and buffers created later are added by deafult to this function unless the user indicates otherwise using the Tiramisu API (by using the low level Tiramisu API and by providing a different function as input to the API).
Definition at line 94 of file expr.h.
set_loop_iterator_type()
static void tiramisu::global::set_loop_iterator_type (primitive_t t) inline static
Definition at line 130 of file expr.h.
The documentation for this class was generated from the following file:
expr.h