Tiramisu Compiler: tiramisu::expr Class Reference
tiramisu::expr Class Reference
A class to represent tiramisu expressions.
#include <expr.h>
Inherited by tiramisu::sync, and tiramisu::var.
Public Member Functions
expr ()
Create an undefined expression.
expr (tiramisu::op_t o, tiramisu::primitive_t dtype, tiramisu::expr expr0)
Create a cast expression to type t (a unary operator).
expr (tiramisu::op_t o, tiramisu::expr expr0)
Create an expression for a unary operator.
expr (tiramisu::op_t o, std::string name)
Create an expression for a unary operator that applies on a variable.
expr (tiramisu::op_t o, tiramisu::expr expr0, tiramisu::expr expr1)
Construct an expression for a binary operator.
expr (tiramisu::op_t o, tiramisu::expr expr0, tiramisu::expr expr1, tiramisu::expr expr2)
Construct an expression for a ternary operator.
expr (tiramisu::op_t o, std::string name, std::vector< tiramisu::expr > vec, tiramisu::primitive_t type)
Construct an access or a call.
expr (uint8_t val)
Construct an unsigned 8-bit integer expression.
expr (int8_t val)
Construct a signed 8-bit integer expression.
expr (uint16_t val)
Construct an unsigned 16-bit integer expression.
expr (int16_t val)
Construct a signed 16-bit integer expression.
expr (uint32_t val)
Construct an unsigned 32-bit integer expression.
expr (int32_t val)
Construct a signed 32-bit integer expression.
expr (uint64_t val)
Construct an unsigned 64-bit integer expression.
expr (int64_t val)
Construct a signed 64-bit integer expression.
expr (float val)
Construct a 32-bit float expression.
tiramisu::expr copy () const
Copy an expression.
expr (double val)
Construct a 64-bit float expression.
int64_t get_int_val () const
double get_double_val () const
const tiramisu::expr & get_operand (int i) const
Return the value of the i 'th operand of the expression.
int get_n_arg () const
Return the number of arguments of the operator.
tiramisu::expr_t get_expr_type () const
Return the type of the expression (tiramisu::expr_type).
tiramisu::primitive_t get_data_type () const
Get the data type of the expression.
const std::string & get_name () const
Get the name of the ID or the variable represented by this expressions.
void set_name (std::string &name)
tiramisu::expr replace_op_in_expr (const std::string &to_replace, const std::string &replace_with)
tiramisu::op_t get_op_type () const
Get the type of the operator (tiramisu::op_t).
const std::vector< tiramisu::expr > & get_access () const
Return a vector of the access of the computation or array.
const std::vector< tiramisu::expr > & get_arguments () const
Return the arguments of an external function call.
int get_n_dim_access () const
Get the number of dimensions in the access vector.
bool is_defined () const
Return true if the expression is defined.
bool is_equal (tiramisu::expr e) const
Return true if e is identical to this expression.
expr operator+ (tiramisu::expr other) const
Addition.
expr operator- (tiramisu::expr other) const
Subtraction.
expr operator/ (tiramisu::expr other) const
Division.
expr operator* (tiramisu::expr other) const
Multiplication.
expr operator% (tiramisu::expr other) const
Modulo.
expr operator>> (tiramisu::expr other) const
Right shift operator.
expr operator<< (tiramisu::expr other) const
Left shift operator.
tiramisu::expr operator && (tiramisu::expr e1) const
Logical and of two expressions.
tiramisu::expr operator|| (tiramisu::expr e1) const
Logical and of two expressions.
tiramisu::expr operator- () const
Expression multiplied by (-1).
tiramisu::expr operator! () const
Logical NOT of an expression.
tiramisu::expr & operator= (tiramisu::expr const &)
tiramisu::expr operator< (tiramisu::expr e1) const
Less than operator.
tiramisu::expr operator<= (tiramisu::expr e1) const
Less than or equal operator.
tiramisu::expr operator> (tiramisu::expr e1) const
Greater than operator.
tiramisu::expr operator>= (tiramisu::expr e1) const
Greater than or equal operator.
void set_access (std::vector< tiramisu::expr > vector)
Set the access of a computation or an array.
void set_access_dimension (int i, tiramisu::expr acc)
Set an element of the vector of accesses of a computation.
void set_arguments (std::vector< tiramisu::expr > vector)
Set the arguments of an external function call.
void dump (bool exhaustive) const
Dump the object on standard output (dump most of the fields of the expression class).
bool is_constant () const
Return true if this expression is a literal constant (i.e., 0, 1, 2, ...).
bool is_unbounded () const
tiramisu::expr simplify () const
Simplify the expression.
std::string to_str () const
expr substitute (std::vector< std::pair< var, expr >> substitutions) const
Returns a new expression where for every (var, sub) pair in substitutions, var in the original expression is replaced by sub.
expr substitute_access (std::string original, std::string substitute) const
Returns an expression where every access to a computation named original is replaced with an access to a computation named substitute, with the same access indices.
expr apply_to_operands (std::function< expr(const expr &)> f) const
uint8_t get_uint8_value () const
Return the actual value of the expression.
int8_t get_int8_value () const
Return the actual value of the expression.
uint16_t get_uint16_value () const
Return the actual value of the expression.
int16_t get_int16_value () const
Return the actual value of the expression.
uint32_t get_uint32_value () const
Return the actual value of the expression.
int32_t get_int32_value () const
Return the actual value of the expression.
uint64_t get_uint64_value () const
Return the actual value of the expression.
int64_t get_int64_value () const
Return the actual value of the expression.
float get_float32_value () const
Return the actual value of the expression.
double get_float64_value () const
Return the actual value of the expression.
tiramisu::expr operator== (tiramisu::expr e1) const
Comparison operator.
tiramisu::expr operator!= (tiramisu::expr e1) const
Comparison operator.
Static Public Member Functions
static expr unbounded ()
Create a variable that can be used that a dimension is unbounded.
Protected Attributes
std::string name
Identifier name.
tiramisu::primitive_t dtype
Data type.
tiramisu::expr_t etype
The type of the expression.
Detailed Description
A class to represent tiramisu expressions.
Definition at line 150 of file expr.h.
Constructor & Destructor Documentation
expr() [1/17]
tiramisu::expr::expr () inline
Create an undefined expression.
Definition at line 231 of file expr.h.
References tiramisu::e_none, tiramisu::o_none, and tiramisu::p_none.
Referenced by simplify().
expr() [2/17]
tiramisu::expr::expr (tiramisu::op_t o, tiramisu::primitive_t dtype, tiramisu::expr expr0) inline
Create a cast expression to type t (a unary operator).
Definition at line 243 of file expr.h.
References dtype, tiramisu::e_op, and tiramisu::o_cast.
expr() [3/17]
tiramisu::expr::expr (tiramisu::op_t o, tiramisu::expr expr0) inline
Create an expression for a unary operator.
Definition at line 258 of file expr.h.
References tiramisu::e_op, get_data_type(), tiramisu::o_cast, tiramisu::o_floor, tiramisu::p_float32, and tiramisu::p_float64.
expr() [4/17]
tiramisu::expr::expr (tiramisu::op_t o, std::string name) inline
Create an expression for a unary operator that applies on a variable.
For example: allocate(A) or free(B).
Definition at line 277 of file expr.h.
References tiramisu::e_op, name, and tiramisu::p_none.
expr() [5/17]
tiramisu::expr::expr (tiramisu::op_t o, tiramisu::expr expr0, tiramisu::expr expr1) inline
Construct an expression for a binary operator.
Definition at line 290 of file expr.h.
References tiramisu::e_op, and get_data_type().
expr() [6/17]
tiramisu::expr::expr (tiramisu::op_t o, tiramisu::expr expr0, tiramisu::expr expr1, tiramisu::expr expr2) inline
Construct an expression for a ternary operator.
Definition at line 307 of file expr.h.
References tiramisu::e_op, and get_data_type().
expr() [7/17]
tiramisu::expr::expr (tiramisu::op_t o, std::string name, std::vector< tiramisu::expr > vec, tiramisu::primitive_t type) inline
Construct an access or a call.
Definition at line 325 of file expr.h.
References tiramisu::e_op, name, tiramisu::o_access, tiramisu::o_address_of, tiramisu::o_buffer, tiramisu::o_call, tiramisu::o_lin_index, set_access(), and set_arguments().
expr() [8/17]
tiramisu::expr::expr (uint8_t val) inline
Construct an unsigned 8-bit integer expression.
Definition at line 361 of file expr.h.
References tiramisu::e_val, tiramisu::o_none, tiramisu::p_uint8, and uint8_value.
expr() [9/17]
tiramisu::expr::expr (int8_t val) inline
Construct a signed 8-bit integer expression.
Definition at line 374 of file expr.h.
References tiramisu::e_val, int8_value, tiramisu::o_none, and tiramisu::p_int8.
expr() [10/17]
tiramisu::expr::expr (uint16_t val) inline
Construct an unsigned 16-bit integer expression.
Definition at line 387 of file expr.h.
References tiramisu::e_val, tiramisu::o_none, tiramisu::p_uint16, and uint16_value.
expr() [11/17]
tiramisu::expr::expr (int16_t val) inline
Construct a signed 16-bit integer expression.
Definition at line 400 of file expr.h.
References tiramisu::e_val, int16_value, tiramisu::o_none, and tiramisu::p_int16.
expr() [12/17]
tiramisu::expr::expr (uint32_t val) inline
Construct an unsigned 32-bit integer expression.
Definition at line 413 of file expr.h.
References tiramisu::e_val, tiramisu::o_none, tiramisu::p_uint32, and uint32_value.
expr() [13/17]
tiramisu::expr::expr (int32_t val) inline
Construct a signed 32-bit integer expression.
Definition at line 426 of file expr.h.
References tiramisu::e_val, int32_value, tiramisu::o_none, and tiramisu::p_int32.
expr() [14/17]
tiramisu::expr::expr (uint64_t val) inline
Construct an unsigned 64-bit integer expression.
Definition at line 439 of file expr.h.
References tiramisu::e_val, tiramisu::o_none, tiramisu::p_uint64, and uint64_value.
expr() [15/17]
tiramisu::expr::expr (int64_t val) inline
Construct a signed 64-bit integer expression.
Definition at line 452 of file expr.h.
References tiramisu::e_val, int64_value, tiramisu::o_none, and tiramisu::p_int64.
expr() [16/17]
tiramisu::expr::expr (float val) inline
Construct a 32-bit float expression.
Definition at line 465 of file expr.h.
References tiramisu::e_val, float32_value, tiramisu::o_none, and tiramisu::p_float32.
expr() [17/17]
tiramisu::expr::expr (double val) inline
Construct a 64-bit float expression.
Definition at line 483 of file expr.h.
References tiramisu::e_val, float64_value, tiramisu::o_none, and tiramisu::p_float64.
Member Function Documentation
apply_to_operands()
expr tiramisu::expr::apply_to_operands (std::function< expr(const expr &)> f) const inline
Definition at line 1609 of file expr.h.
copy()
tiramisu::expr tiramisu::expr::copy () const
Copy an expression.
dump()
void tiramisu::expr::dump (bool exhaustive) const inline
Dump the object on standard output (dump most of the fields of the expression class).
This is mainly useful for debugging. If exhaustive is set to true, all the fields of the class are printed. This is useful to find potential initialization problems.
Definition at line 1014 of file expr.h.
References dump(), tiramisu::e_none, tiramisu::e_op, tiramisu::e_sync, tiramisu::e_val, tiramisu::e_var, get_access(), get_arguments(), get_data_type(), get_expr_type(), get_float32_value(), get_float64_value(), get_int16_value(), get_int32_value(), get_int64_value(), get_int8_value(), get_n_arg(), get_name(), get_op_type(), get_operand(), get_uint16_value(), get_uint32_value(), get_uint64_value(), get_uint8_value(), is_defined(), tiramisu::o_access, tiramisu::o_address, tiramisu::o_address_of, tiramisu::o_allocate, tiramisu::o_call, tiramisu::o_free, tiramisu::o_lin_index, tiramisu::p_float32, tiramisu::p_float64, tiramisu::p_int16, tiramisu::p_int32, tiramisu::p_int64, tiramisu::p_int8, tiramisu::p_uint16, tiramisu::p_uint32, tiramisu::p_uint64, tiramisu::p_uint8, tiramisu::str_from_tiramisu_type_expr(), tiramisu::str_from_tiramisu_type_primitive(), tiramisu::str_tiramisu_type_op(), and to_str().
Referenced by dump(), and to_str().
get_access()
const std::vector<tiramisu::expr>& tiramisu::expr::get_access () const inline
Return a vector of the access of the computation or array.
For example, for the computation C0(i,j), this function will return the vector {i, j} where i and j are both tiramisu expressions. For a buffer access A[i+1,j], it will return also {i+1, j}.
Definition at line 755 of file expr.h.
References tiramisu::e_op, get_expr_type(), get_op_type(), tiramisu::o_access, tiramisu::o_address_of, tiramisu::o_buffer, tiramisu::o_dummy, and tiramisu::o_lin_index.
Referenced by dump(), and to_str().
get_arguments()
const std::vector<tiramisu::expr>& tiramisu::expr::get_arguments () const inline
Return the arguments of an external function call.
Definition at line 768 of file expr.h.
References tiramisu::e_op, get_expr_type(), get_op_type(), and tiramisu::o_call.
Referenced by dump(), and to_str().
get_data_type()
tiramisu::primitive_t tiramisu::expr::get_data_type () const inline
Get the data type of the expression.
Definition at line 687 of file expr.h.
References dtype.
Referenced by dump(), expr(), get_double_val(), get_float32_value(), get_float64_value(), get_int16_value(), get_int32_value(), get_int64_value(), get_int8_value(), get_int_val(), get_uint16_value(), get_uint32_value(), get_uint64_value(), get_uint8_value(), is_equal(), tiramisu::operator*(), tiramisu::operator+(), tiramisu::operator-(), simplify(), and to_str().
get_double_val()
double tiramisu::expr::get_double_val () const inline
Definition at line 632 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), get_float32_value(), get_float64_value(), tiramisu::p_float32, tiramisu::p_float64, and result.
Referenced by is_equal().
get_expr_type()
tiramisu::expr_t tiramisu::expr::get_expr_type () const inline
Return the type of the expression (tiramisu::expr_type).
Definition at line 679 of file expr.h.
References etype.
Referenced by dump(), get_access(), get_arguments(), get_double_val(), get_float32_value(), get_float64_value(), get_int16_value(), get_int32_value(), get_int64_value(), get_int8_value(), get_int_val(), get_n_arg(), get_n_dim_access(), get_name(), get_operand(), get_uint16_value(), get_uint32_value(), get_uint64_value(), get_uint8_value(), is_constant(), set_name(), simplify(), and to_str().
get_float32_value()
float tiramisu::expr::get_float32_value () const inline
Return the actual value of the expression.
Definition at line 561 of file expr.h.
References tiramisu::e_val, float32_value, get_data_type(), get_expr_type(), and tiramisu::p_float32.
Referenced by dump(), get_double_val(), get_int_val(), and to_str().
get_float64_value()
double tiramisu::expr::get_float64_value () const inline
Return the actual value of the expression.
Definition at line 569 of file expr.h.
References tiramisu::e_val, float64_value, get_data_type(), get_expr_type(), and tiramisu::p_float64.
Referenced by dump(), get_double_val(), get_int_val(), and to_str().
get_int16_value()
int16_t tiramisu::expr::get_int16_value () const inline
Return the actual value of the expression.
Definition at line 521 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), int16_value, and tiramisu::p_int16.
Referenced by dump(), get_int_val(), and to_str().
get_int32_value()
int32_t tiramisu::expr::get_int32_value () const inline
Return the actual value of the expression.
Definition at line 537 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), int32_value, and tiramisu::p_int32.
Referenced by dump(), get_int_val(), and to_str().
get_int64_value()
int64_t tiramisu::expr::get_int64_value () const inline
Return the actual value of the expression.
Definition at line 553 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), int64_value, and tiramisu::p_int64.
Referenced by dump(), get_int_val(), and to_str().
get_int8_value()
int8_t tiramisu::expr::get_int8_value () const inline
Return the actual value of the expression.
Definition at line 505 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), int8_value, and tiramisu::p_int8.
Referenced by dump(), get_int_val(), and to_str().
get_int_val()
int64_t tiramisu::expr::get_int_val () const inline
Definition at line 578 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), get_float32_value(), get_float64_value(), get_int16_value(), get_int32_value(), get_int64_value(), get_int8_value(), get_uint16_value(), get_uint32_value(), get_uint64_value(), get_uint8_value(), tiramisu::p_float32, tiramisu::p_float64, tiramisu::p_int16, tiramisu::p_int32, tiramisu::p_int64, tiramisu::p_int8, tiramisu::p_uint16, tiramisu::p_uint32, tiramisu::p_uint64, tiramisu::p_uint8, and result.
Referenced by is_equal(), and simplify().
get_n_arg()
int tiramisu::expr::get_n_arg () const inline
Return the number of arguments of the operator.
Definition at line 669 of file expr.h.
References tiramisu::e_op, and get_expr_type().
Referenced by dump().
get_n_dim_access()
int tiramisu::expr::get_n_dim_access () const inline
Get the number of dimensions in the access vector.
Definition at line 779 of file expr.h.
References tiramisu::e_op, get_expr_type(), get_op_type(), and tiramisu::o_access.
get_name()
const std::string& tiramisu::expr::get_name () const inline
Get the name of the ID or the variable represented by this expressions.
Definition at line 695 of file expr.h.
References tiramisu::e_var, get_expr_type(), get_op_type(), name, tiramisu::o_access, tiramisu::o_address, tiramisu::o_address_of, tiramisu::o_allocate, tiramisu::o_buffer, tiramisu::o_call, tiramisu::o_dummy, tiramisu::o_free, and tiramisu::o_lin_index.
Referenced by dump(), tiramisu::computation::fuse_after(), is_unbounded(), and to_str().
get_op_type()
tiramisu::op_t tiramisu::expr::get_op_type () const inline
Get the type of the operator (tiramisu::op_t).
Definition at line 742 of file expr.h.
Referenced by dump(), get_access(), get_arguments(), get_n_dim_access(), get_name(), set_name(), simplify(), and to_str().
get_operand()
const tiramisu::expr& tiramisu::expr::get_operand (int i) const inline
Return the value of the i 'th operand of the expression.
i can be 0, 1 or 2.
Definition at line 658 of file expr.h.
References tiramisu::e_op, and get_expr_type().
Referenced by dump(), replace_op_in_expr(), simplify(), and to_str().
get_uint16_value()
uint16_t tiramisu::expr::get_uint16_value () const inline
Return the actual value of the expression.
Definition at line 513 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), tiramisu::p_uint16, and uint16_value.
Referenced by dump(), get_int_val(), and to_str().
get_uint32_value()
uint32_t tiramisu::expr::get_uint32_value () const inline
Return the actual value of the expression.
Definition at line 529 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), tiramisu::p_uint32, and uint32_value.
Referenced by dump(), get_int_val(), and to_str().
get_uint64_value()
uint64_t tiramisu::expr::get_uint64_value () const inline
Return the actual value of the expression.
Definition at line 545 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), tiramisu::p_uint64, and uint64_value.
Referenced by dump(), get_int_val(), and to_str().
get_uint8_value()
uint8_t tiramisu::expr::get_uint8_value () const inline
Return the actual value of the expression.
Definition at line 497 of file expr.h.
References tiramisu::e_val, get_data_type(), get_expr_type(), tiramisu::p_uint8, and uint8_value.
Referenced by dump(), get_int_val(), and to_str().
is_constant()
bool tiramisu::expr::is_constant () const inline
Return true if this expression is a literal constant (i.e., 0, 1, 2, ...).
Definition at line 1153 of file expr.h.
References tiramisu::e_val, and get_expr_type().
is_defined()
bool tiramisu::expr::is_defined () const inline
Return true if the expression is defined.
Definition at line 790 of file expr.h.
Referenced by dump().
is_equal()
bool tiramisu::expr::is_equal (tiramisu::expr e) const inline
Return true if e is identical to this expression.
Definition at line 798 of file expr.h.
References dtype, tiramisu::e_val, etype, float32_value, float64_value, get_data_type(), get_double_val(), get_int_val(), int16_value, int32_value, int64_value, int8_value, name, tiramisu::p_float32, tiramisu::p_float64, uint16_value, uint32_value, uint64_value, and uint8_value.
is_unbounded()
bool tiramisu::expr::is_unbounded () const inline
Definition at line 1161 of file expr.h.
References get_name().
operator &&()
tiramisu::expr tiramisu::expr::operator&& (tiramisu::expr e1) const inline
Logical and of two expressions.
Definition at line 899 of file expr.h.
References tiramisu::o_logical_and.
operator!()
tiramisu::expr tiramisu::expr::operator! () const inline
Logical NOT of an expression.
Definition at line 923 of file expr.h.
References tiramisu::o_logical_not.
operator!=()
tiramisu::expr tiramisu::expr::operator!= (tiramisu::expr e1) const inline
Comparison operator.
Definition at line 938 of file expr.h.
References tiramisu::o_ne.
operator%()
expr tiramisu::expr::operator% (tiramisu::expr other) const
Modulo.
operator*()
expr tiramisu::expr::operator* (tiramisu::expr other) const
Multiplication.
operator+()
expr tiramisu::expr::operator+ (tiramisu::expr other) const
Addition.
operator-() [1/2]
expr tiramisu::expr::operator- (tiramisu::expr other) const
Subtraction.
operator-() [2/2]
tiramisu::expr tiramisu::expr::operator- () const inline
Expression multiplied by (-1).
Definition at line 915 of file expr.h.
References tiramisu::o_minus.
operator/()
expr tiramisu::expr::operator/ (tiramisu::expr other) const
Division.
operator<()
tiramisu::expr tiramisu::expr::operator< (tiramisu::expr e1) const inline
Less than operator.
Definition at line 947 of file expr.h.
References tiramisu::o_lt.
operator<<()
expr tiramisu::expr::operator<< (tiramisu::expr other) const
Left shift operator.
operator<=()
tiramisu::expr tiramisu::expr::operator<= (tiramisu::expr e1) const inline
Less than or equal operator.
Definition at line 955 of file expr.h.
References tiramisu::o_le.
operator=()
tiramisu::expr& tiramisu::expr::operator= (tiramisu::expr const &)
operator==()
tiramisu::expr tiramisu::expr::operator== (tiramisu::expr e1) const inline
Comparison operator.
Definition at line 934 of file expr.h.
References tiramisu::o_eq.
operator>()
tiramisu::expr tiramisu::expr::operator> (tiramisu::expr e1) const inline
Greater than operator.
Definition at line 963 of file expr.h.
References tiramisu::o_gt.
operator>=()
tiramisu::expr tiramisu::expr::operator>= (tiramisu::expr e1) const inline
Greater than or equal operator.
Definition at line 971 of file expr.h.
References tiramisu::o_ge.
operator>>()
expr tiramisu::expr::operator>> (tiramisu::expr other) const
Right shift operator.
operator||()
tiramisu::expr tiramisu::expr::operator|| (tiramisu::expr e1) const inline
Logical and of two expressions.
Definition at line 907 of file expr.h.
References tiramisu::o_logical_or.
replace_op_in_expr()
tiramisu::expr tiramisu::expr::replace_op_in_expr (const std::string & to_replace, const std::string & replace_with) inline
Definition at line 725 of file expr.h.
References get_operand(), and replace_op_in_expr().
Referenced by replace_op_in_expr().
set_access()
void tiramisu::expr::set_access (std::vector< tiramisu::expr > vector) inline
Set the access of a computation or an array.
For example, for the computation C0, this function can set the vector {i, j} as an access vector. The result is that the computation C0 is accessed with C0(i,j).
Definition at line 983 of file expr.h.
Referenced by expr().
set_access_dimension()
void tiramisu::expr::set_access_dimension (int i, tiramisu::expr acc) inline
Set an element of the vector of accesses of a computation.
This changes only one dimension of the access vector.
Definition at line 992 of file expr.h.
set_arguments()
void tiramisu::expr::set_arguments (std::vector< tiramisu::expr > vector) inline
Set the arguments of an external function call.
For example, for the call my_external(C0, 1, C1(i,j)), vector should be {C0, 1, C1(i,j)}.
Definition at line 1003 of file expr.h.
Referenced by expr().
set_name()
void tiramisu::expr::set_name (std::string & name) inline
Definition at line 711 of file expr.h.
References tiramisu::e_var, get_expr_type(), get_op_type(), name, tiramisu::o_access, tiramisu::o_address_of, tiramisu::o_allocate, tiramisu::o_call, tiramisu::o_dummy, tiramisu::o_free, and tiramisu::o_lin_index.
simplify()
tiramisu::expr tiramisu::expr::simplify () const inline
Simplify the expression.
Definition at line 1172 of file expr.h.
References tiramisu::e_none, tiramisu::e_op, tiramisu::e_val, tiramisu::e_var, expr(), get_data_type(), get_expr_type(), get_int_val(), get_op_type(), get_operand(), tiramisu::o_abs, tiramisu::o_access, tiramisu::o_acos, tiramisu::o_add, tiramisu::o_address, tiramisu::o_allocate, tiramisu::o_asin, tiramisu::o_atan, tiramisu::o_call, tiramisu::o_cast, tiramisu::o_ceil, tiramisu::o_cond, tiramisu::o_cos, tiramisu::o_div, tiramisu::o_eq, tiramisu::o_expo, tiramisu::o_floor, tiramisu::o_free, tiramisu::o_ge, tiramisu::o_gt, tiramisu::o_le, tiramisu::o_left_shift, tiramisu::o_lerp, tiramisu::o_log, tiramisu::o_logical_and, tiramisu::o_logical_not, tiramisu::o_logical_or, tiramisu::o_lt, tiramisu::o_max, tiramisu::o_min, tiramisu::o_minus, tiramisu::o_mod, tiramisu::o_mul, tiramisu::o_ne, tiramisu::o_right_shift, tiramisu::o_round, tiramisu::o_select, tiramisu::o_sin, tiramisu::o_sqrt, tiramisu::o_sub, tiramisu::o_tan, tiramisu::o_trunc, tiramisu::p_int32, and simplify().
Referenced by simplify().
substitute()
expr tiramisu::expr::substitute (std::vector< std::pair< var, expr >> substitutions) const
Returns a new expression where for every (var, sub) pair in substitutions, var in the original expression is replaced by sub.
For example: if substitutions is {(i, 5), (j, i)}, and the original expression is i + j * 2, then this method returns 5 + i * 2.
Referenced by tiramisu::computation::operator()().
substitute_access()
expr tiramisu::expr::substitute_access (std::string original, std::string substitute) const
Returns an expression where every access to a computation named original is replaced with an access to a computation named substitute, with the same access indices.
An example where this is useful is when modifying a computation that was designed to work with a host buffer to work with a GPU buffer.
to_str()
std::string tiramisu::expr::to_str () const inline
Definition at line 1299 of file expr.h.
References dump(), tiramisu::e_none, tiramisu::e_op, tiramisu::e_sync, tiramisu::e_val, tiramisu::e_var, get_access(), get_arguments(), get_data_type(), get_expr_type(), get_float32_value(), get_float64_value(), get_int16_value(), get_int32_value(), get_int64_value(), get_int8_value(), get_name(), get_op_type(), get_operand(), get_uint16_value(), get_uint32_value(), get_uint64_value(), get_uint8_value(), tiramisu::o_abs, tiramisu::o_access, tiramisu::o_acos, tiramisu::o_add, tiramisu::o_address, tiramisu::o_address_of, tiramisu::o_allocate, tiramisu::o_asin, tiramisu::o_atan, tiramisu::o_buffer, tiramisu::o_call, tiramisu::o_cast, tiramisu::o_ceil, tiramisu::o_cond, tiramisu::o_cos, tiramisu::o_div, tiramisu::o_eq, tiramisu::o_expo, tiramisu::o_floor, tiramisu::o_free, tiramisu::o_ge, tiramisu::o_gt, tiramisu::o_le, tiramisu::o_left_shift, tiramisu::o_lerp, tiramisu::o_lin_index, tiramisu::o_log, tiramisu::o_logical_and, tiramisu::o_logical_not, tiramisu::o_logical_or, tiramisu::o_lt, tiramisu::o_max, tiramisu::o_memcpy, tiramisu::o_min, tiramisu::o_minus, tiramisu::o_mod, tiramisu::o_mul, tiramisu::o_ne, tiramisu::o_right_shift, tiramisu::o_round, tiramisu::o_select, tiramisu::o_sin, tiramisu::o_sqrt, tiramisu::o_sub, tiramisu::o_tan, tiramisu::o_trunc, tiramisu::p_float32, tiramisu::p_float64, tiramisu::p_int16, tiramisu::p_int32, tiramisu::p_int64, tiramisu::p_int8, tiramisu::p_uint16, tiramisu::p_uint32, tiramisu::p_uint64, tiramisu::p_uint8, and to_str().
Referenced by dump(), and to_str().
unbounded()
static expr tiramisu::expr::unbounded () inline static
Create a variable that can be used that a dimension is unbounded.
i < tiramisu::expr::unbounded() means that i does not have an upper bound. i > tiramisu::expr::unbounded() means that i does not have a lower bound.
Definition at line 1628 of file expr.h.
References dtype, tiramisu::e_val, etype, name, tiramisu::o_none, and tiramisu::p_none.
Member Data Documentation
dtype
tiramisu::primitive_t tiramisu::expr::dtype protected
Data type.
Definition at line 219 of file expr.h.
Referenced by tiramisu::computation::computation(), expr(), get_data_type(), is_equal(), tiramisu::sync::sync(), and unbounded().
etype
tiramisu::expr_t tiramisu::expr::etype protected
The type of the expression.
Definition at line 224 of file expr.h.
Referenced by get_expr_type(), is_equal(), tiramisu::sync::sync(), and unbounded().
float32_value
float tiramisu::expr::float32_value
Definition at line 182 of file expr.h.
Referenced by expr(), get_float32_value(), and is_equal().
float64_value
double tiramisu::expr::float64_value
Definition at line 183 of file expr.h.
Referenced by expr(), get_float64_value(), and is_equal().
int16_value
int16_t tiramisu::expr::int16_value
Definition at line 177 of file expr.h.
Referenced by expr(), get_int16_value(), and is_equal().
int32_value
int32_t tiramisu::expr::int32_value
Definition at line 179 of file expr.h.
Referenced by expr(), get_int32_value(), and is_equal().
int64_value
int64_t tiramisu::expr::int64_value
Definition at line 181 of file expr.h.
Referenced by expr(), get_int64_value(), and is_equal().
int8_value
int8_t tiramisu::expr::int8_value
Definition at line 175 of file expr.h.
Referenced by expr(), get_int8_value(), and is_equal().
name
std::string tiramisu::expr::name protected
Identifier name.
Definition at line 214 of file expr.h.
Referenced by expr(), get_name(), is_equal(), set_name(), and unbounded().
uint16_value
uint16_t tiramisu::expr::uint16_value
Definition at line 176 of file expr.h.
Referenced by expr(), get_uint16_value(), and is_equal().
uint32_value
uint32_t tiramisu::expr::uint32_value
Definition at line 178 of file expr.h.
Referenced by expr(), get_uint32_value(), and is_equal().
uint64_value
uint64_t tiramisu::expr::uint64_value
Definition at line 180 of file expr.h.
Referenced by expr(), get_uint64_value(), and is_equal().
uint8_value
uint8_t tiramisu::expr::uint8_value
Definition at line 174 of file expr.h.
Referenced by expr(), get_uint8_value(), and is_equal().
The documentation for this class was generated from the following file:
expr.h