Tiramisu Compiler: tiramisu::HalideCodegenOutput Struct Reference
tiramisu::HalideCodegenOutput Struct Reference
#include <core.h>
Public Member Functions
HalideCodegenOutput (const std::map< std::string, tiramisu::computation * > &computations, const std::map< std::string, tiramisu::constant * > &constants, const std::map< std::string, tiramisu::buffer * > &buffers)
Public Attributes
std::map< std::string, tiramisu::computation * > computation_list
std::map< std::string, tiramisu::constant * > constant_list
std::map< std::string, tiramisu::buffer * > output_buffers
Detailed Description
Definition at line 44 of file core.h.
Constructor & Destructor Documentation
tiramisu::HalideCodegenOutput::HalideCodegenOutput (const std::map< std::string, tiramisu::computation * > & computations, const std::map< std::string, tiramisu::constant * > & constants, const std::map< std::string, tiramisu::buffer * > & buffers) inline
Definition at line 50 of file core.h.
References tiramisu::generate_new_computation_name(), tiramisu::get_computation_annotated_in_a_node(), tiramisu::halide_pipeline_to_tiramisu_function(), tiramisu::isl_map_add_free_var(), tiramisu::loop_level_into_dynamic_dimension(), tiramisu::loop_level_into_static_dimension(), and tiramisu::split_string().
Member Data Documentation
std::map<std::string, tiramisu::computation *> tiramisu::HalideCodegenOutput::computation_list
Definition at line 46 of file core.h.
std::map<std::string, tiramisu::constant *> tiramisu::HalideCodegenOutput::constant_list
Definition at line 47 of file core.h.
std::map<std::string, tiramisu::buffer *> tiramisu::HalideCodegenOutput::output_buffers
Definition at line 48 of file core.h.
The documentation for this struct was generated from the following file:
core.h